export const metadata = {
  title: "About-us",
  description: "Generated by Next.js",
};

export default function AboutUSLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {children}
      &copy; Next JS is great!
    </div>
  );
}
